name: Build Android APK (Debug)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      # Descarga Gradle 8.7 (compatible con AGP 8.5) y lo añade al PATH
      - name: Install Gradle 8.7
        run: |
          curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Build debug APK
        run: |
          gradle --version
          gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: CVReelApp-debug-apk
          path: app/build/outputs/apk/debug/*.apk
